default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "wink") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: wink_development

test:
  <<: *default
  database: wink_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "wink") %>
    # migrations_paths: db/migrate is not necessary, because it's the default value 
  cache:
    <<: *default
    database: <%= ENV.fetch("CACHE_DATABASE_NAME", "wink_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "wink_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("CABLE_DATABASE_NAME", "wink_cable") %>
    migrations_paths: db/cable_migrate